# Count the number of days in each month from the Spatial data based on the data type. 
# Or count the days in a month when observation was carried  out.

install.packages("foreign")
library(foreign)
install.packages("tidyverse")
library(tidyverse)

# Export the shapefile to dbf format in ArcGIS Pro and r can easily read the .dbf file.
df <- read.dbf("D:/olym/Tidyverse_In_SpatialData/OLYM_SummaryWaypoints.dbf", as.is = FALSE)

glimpse(df)

head(df)

# Closely observe the variables or fields that can be used to calculate the total number of days in the spatial data.
# We choose only two variables - TIME and flight_id
# We used mutate_at before, but funs() of mutate_at was deprecated. So, we have to use select() to pick the required columns.
df1 <- df %>% select(TIME, flight_id)

# Have to change the columns to characters because TIME is in date format and flight_id as factor.
# TIME is in the format 2021-07-29
df1 <- data.frame(lapply(df1, as.character), stringsAsFactors=FALSE)

glimpse(df1)

# Now, time is in the format '2021-07-29'.
# Need to separate the variable TIME. We will get '2021', '07' and '29' - all as characters
df1 <- df1 %>% separate(TIME, c('Year', 'Month', 'Day'))

glimpse(df1)

head(df1)

# Combine or concatenate Year and Month, using "-" in between them. We will get '2021-07' as character. 
df1 <- df1 %>% unite(YearMonth, Year, Month, sep = "-")

glimpse(df1)

head(df1)

# Apply group_by with YearMonth as each YearMonth is unique, and count the 'Day' within each group by n_distinct.
# Distinct Days are counted within that Month-Year and thus gives the total days month-wise.
# Days when the data was obtained in the shapefile. 
days_month <- df1 %>%
  group_by(YearMonth) %>%
  summarize(Number_days = n_distinct(Day))

days_month

#--------------------------------------------------------------------------------------------
# The analysis required to calculate the average of each day of the week, i.e. average results on 
# Monday, Tuesday, ..., Sunday. So, we need to calculate the number of Mondays, Sundays, ..., etc.
# within the period of investigation. We only have date as one variable. 

# Read the dbf file generated by ArcGIS Pro.
df1 <- read.dbf("D:/olym/Tidyverse_In_SpatialData/OLYM_SummaryWaypoints.dbf", as.is = FALSE)

glimpse(df1)
head(df1)
dim(df1)

# TIME variable is in date format. So, convert the date to the day of the week in a new column, 'day_name' of the dataframe.
df1$day_name <- weekdays(df1$TIME)

# Check the characteristics of column containing names of day.
unique(df1$day_name) # This gives the seven days of the week. 
head(df1)
dim(df1)

# Cross check one value or row with TIME == '2021-08-08'; this should be Tuesday. 
df1[df1$TIME == '2021-08-03',]

# Select only few required columns from the dataframe. 
df2 <- df1 %>% select(TIME, flight_id, day_name)
glimpse(df2)

# Convert the columns data into character data type. 
df2 <- data.frame(lapply(df2, as.character), stringsAsFactors=FALSE)
glimpse(df2)

# TIME has changed to character format, so separate '2021-08-03' into Year, Month an Day.
df2 <- df2 %>% separate(TIME, c('Year', 'Month', 'Day'))
glimpse(df2)
head(df2)

# Combine or concatenate Year and Month as '2021-08'. 
df2 <- df2 %>% unite(YearMonth, Year, Month, sep = "-")
glimpse(df2)
head(df2)

# Need to count the days of week in each month; each month is unique because they are represented by
# "2021-07", "2021-08", etc. Need to count the number of Fridays, Mondays, etc. in that month. 
# Apply filter() to select only that month, then apply group_by() the name of the day of the week
# then count the Day because Day will be from 1 to 31 in a month. So, Friday can be Friday 2, Friday 9, ...
# for the month of "2021-07". n_distinct() count the number of unique occurrences. Repeat for each month.   

number_days1 <- df2 %>%
  filter(YearMonth=="2021-07") %>%
  group_by(day_name) %>%
  summarize(number_Jul2021 = n_distinct(Day))
number_days1
# number_days1 has only Friday, Saturday, Thursday, Tuesday and Wednesday.

number_days2 <- df2 %>%
  filter(YearMonth=="2021-08") %>%
  group_by(day_name) %>%
  summarize(number_Aug2021 = n_distinct(Day))
number_days2

number_days3 <- df2 %>%
  filter(YearMonth=="2021-09") %>%
  group_by(day_name) %>%
  summarize(number_Sept2021 = n_distinct(Day))
number_days3

number_days4 <- df2 %>%
  filter(YearMonth=="2021-10") %>%
  group_by(day_name) %>%
  summarize(number_Oct2021 = n_distinct(Day))
number_days4

number_days5 <- df2 %>%
  filter(YearMonth=="2021-11") %>%
  group_by(day_name) %>%
  summarize(number_Nov2021 = n_distinct(Day))
number_days5

number_days6 <- df2 %>%
  filter(YearMonth=="2021-12") %>%
  group_by(day_name) %>%
  summarize(number_Dec2021 = n_distinct(Day))
number_days6

number_days7 <- df2 %>%
  filter(YearMonth=="2022-01") %>%
  group_by(day_name) %>%
  summarize(number_Jan2022 = n_distinct(Day))
number_days7

number_days8 <- df2 %>%
  filter(YearMonth=="2022-02") %>%
  group_by(day_name) %>%
  summarize(number_Feb2022 = n_distinct(Day))
number_days8

number_days9 <- df2 %>%
  filter(YearMonth=="2022-03") %>%
  group_by(day_name) %>%
  summarize(number_Mar2022 = n_distinct(Day))
number_days9

number_days10 <- df2 %>%
  filter(YearMonth=="2022-04") %>%
  group_by(day_name) %>%
  summarize(number_Apr2022 = n_distinct(Day))
number_days10

number_days11 <- df2 %>%
  filter(YearMonth=="2022-05") %>%
  group_by(day_name) %>%
  summarize(number_May2022 = n_distinct(Day))
number_days11

number_days12 <- df2 %>%
  filter(YearMonth=="2022-06") %>%
  group_by(day_name) %>%
  summarize(number_Jun2022 = n_distinct(Day))
number_days12

number_days13 <- df2 %>%
  filter(YearMonth=="2022-07") %>%
  group_by(day_name) %>%
  summarize(number_Jul2022 = n_distinct(Day))
number_days13

number_days14 <- df2 %>%
  filter(YearMonth=="2022-08") %>%
  group_by(day_name) %>%
  summarize(number_Aug2022 = n_distinct(Day))
number_days14

number_days15 <- df2 %>%
  filter(YearMonth=="2022-09") %>%
  group_by(day_name) %>%
  summarize(number_Sept2022 = n_distinct(Day))
number_days15

number_days16 <- df2 %>%
  filter(YearMonth=="2022-10") %>%
  group_by(day_name) %>%
  summarize(number_Oct2022 = n_distinct(Day))
number_days16

number_days17 <- df2 %>%
  filter(YearMonth=="2022-11") %>%
  group_by(day_name) %>%
  summarize(number_Nov2022 = n_distinct(Day))
number_days17

number_days18 <- df2 %>%
  filter(YearMonth=="2022-12") %>%
  group_by(day_name) %>%
  summarize(number_Dec2022 = n_distinct(Day))
number_days18

number_days19 <- df2 %>%
  filter(YearMonth=="2023-01") %>%
  group_by(day_name) %>%
  summarize(number_Jan2023 = n_distinct(Day))
number_days19
# number_days19 has only Monday and Sunday

# Bind the vectors of data into a dataframe w/o number_days1 and number_days19
# because these two do not have complete seven days. So, this creates error while applying cbind. 
table_days <- as.data.frame(cbind(number_days2, number_days3,
                                  number_days4, number_days5, number_days6,
                                  number_days7, number_days8, number_days9,
                                  number_days10, number_days11, number_days12,
                                  number_days13, number_days14, number_days15,
                                  number_days16, number_days17, number_days18))

table_days
# Export the table_days or copy manually to your Excel sheet and manually add the two 
# incomplete vector data, i.e. number_days1 and number_days19

# Now, we have number of Fridays, Mondays, etc. in each month of our data. 
